/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import database.koneksi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rudia
 */
public class frameLaporan extends javax.swing.JFrame {
            koneksi koneksi;
    
            public DefaultTableModel modelTableLaporan;

    /**
     * Creates new form frameLaporan
     */
    public frameLaporan() {
        initComponents();
        this.setLocationRelativeTo(null);
        koneksi = new koneksi();
        modelTableLaporan = new DefaultTableModel();
        tableLaporan.setModel(modelTableLaporan);
        modelTableLaporan.addColumn("Id Laporan");
        modelTableLaporan.addColumn("Jenis Paket");
        modelTableLaporan.addColumn("Nama Pelanggan");
        modelTableLaporan.addColumn("Tanggal Transaksi");
        modelTableLaporan.addColumn("Total");
        tampilDataLaporan();
    }

    public void tampilDataLaporan(){
        try {
            modelTableLaporan.getDataVector().removeAllElements();
            modelTableLaporan.fireTableDataChanged();
            
            PreparedStatement query = koneksi.connect.prepareStatement("SELECT * FROM laporan");
            ResultSet data = query.executeQuery();
            while (data.next()) {                
                Object[] baris = new Object[5];
                baris[0] = data.getString("id_laporan");
                baris[1] = data.getString("jenis_paket");
                baris[2] = data.getString("nama_pelanggan");
                baris[3] = data.getString("tgl_transaksi");
                baris[4] = data.getString("total");
                modelTableLaporan.addRow(baris);
            }
            query.close();
            data.close();
        } catch (Exception e) {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtidlaporan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtjenis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnamapel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttgl = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLaporan = new javax.swing.JTable();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnsimpanPrepare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id Laporan");

        jLabel2.setText("Jenis Paket");

        jLabel3.setText("Nama Pelanggan");

        jLabel4.setText("Tanggal Transaksi");

        jLabel5.setText("Total");

        btnsimpan.setText("Simpan Statement");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        tableLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLaporanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLaporan);

        btnubah.setText("Ubah Data");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus Data");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnsimpanPrepare.setText("Simpan Prepare Statement");
        btnsimpanPrepare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanPrepareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnsimpanPrepare)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtnamapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidlaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtidlaporan, txtjenis, txtnamapel, txttgl, txttotal});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidlaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnubah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnamapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnsimpanPrepare))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, txtidlaporan, txtjenis, txtnamapel, txttgl, txttotal});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        
        try {
            if(txtidlaporan.getText().isEmpty()){
              JOptionPane.showMessageDialog(this, "id laporan belum diisi");
              txtidlaporan.requestFocus();
            }else if(txtjenis.getText().isEmpty()){
              JOptionPane.showMessageDialog(this, "jenis paket belum diisi");
              txtjenis.requestFocus();
            }else if(txtnamapel.getText().isEmpty()){
              JOptionPane.showMessageDialog(this, "nama pelanggan belum diisi");
              txtnamapel.requestFocus();
            }else if(txttgl.getText().isEmpty()){
              JOptionPane.showMessageDialog(this, "tanggal transaksi belum diisi");
              txttgl.requestFocus();
            }else if(txttotal.getText().isEmpty()){
              JOptionPane.showMessageDialog(this, "total belum diisi");
              txttotal.requestFocus();  
            }else{
                String sql ="insert into laporan value('"+txtidlaporan.getText()+"','"+txtjenis.getText()+"','"+txtnamapel.getText()+"','"+txttgl.getText()+"','"+txttotal.getText()+"')";
                koneksi.connect.createStatement().execute(sql);
                tampilDataLaporan();
                JOptionPane.showMessageDialog(this, "data berhasil disimpan");
            }
        } catch (Exception e) {
               JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnsimpanPrepareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanPrepareActionPerformed
        // TODO add your handling code here:
        
           try {
            if(txtidlaporan.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "id belum diisi");
               txtidlaporan.requestFocus();
            } else if(txtjenis.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Jenis Paket belum diisi");
               txtjenis.requestFocus();
            } else if(txtnamapel.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Nama Pelanggan belum diisi");
               txtnamapel.requestFocus();
            } else if(txttgl.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Tanggal Transaksi belum diisi");
               txttgl.requestFocus();
            } else if(txttotal.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Total belum diisi");
               txttotal.requestFocus();
            } else{
               String sqlCari = "SELECT * FROM laporan WHERE id_laporan ='"+txtidlaporan.getText()+"'";
               ResultSet cari = koneksi.connect.createStatement().executeQuery(sqlCari);
               if (cari.next()){
                    JOptionPane.showMessageDialog(this, "ID sudah terdaftar");
                                        
                       txtjenis.setText(cari.getString(2));
                       txtnamapel.setText(cari.getString(3));                   
                       txttgl.setText(cari.getString(4));                   
                       txttotal.setText(cari.getString(5));                   
               }else{
                    String sql = "INSERT INTO laporan VALUE(?,?,?,?,?)";
                    PreparedStatement simpan = koneksi.connect.prepareStatement(sql);
                    simpan.setString(1, txtidlaporan.getText());
                    simpan.setString(2, txtjenis.getText());
                    simpan.setString(3, txtnamapel.getText());
                    simpan.setString(4, txttgl.getText());
                    simpan.setString(5, txttotal.getText());
                    simpan.executeUpdate();
                    tampilDataLaporan();
                    JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
               }
               
           }  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnsimpanPrepareActionPerformed

    private void tableLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLaporanMouseClicked
        // TODO add your handling code here:
        
        int baris = tableLaporan.getSelectedRow();
        String id = tableLaporan.getValueAt(baris, 0).toString();
        String jenis = tableLaporan.getValueAt(baris, 1).toString();
        String namapel = tableLaporan.getValueAt(baris, 2).toString();
        String tgl = tableLaporan.getValueAt(baris, 3).toString();
        String total = tableLaporan.getValueAt(baris, 4).toString();
        txtidlaporan.setText(id);
        txtjenis.setText(jenis);
        txtnamapel.setText(namapel);
        txttgl.setText(tgl);
        txttotal.setText(total);
    }//GEN-LAST:event_tableLaporanMouseClicked

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        try {
            if (
                    (txtidlaporan.getText().isEmpty()) &&
                    (txtjenis.getText().isEmpty()) &&
                    (txtnamapel.getText().isEmpty()) &&
                    (txttgl.getText().isEmpty()) &&
                    (txttotal.getText().isEmpty()) 
               ){
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Terlebih Dahulu");
            }else
            {
                String sql = "UPDATE laporan Set jenis_paket=?,nama_pelanggan=?,tgl_transaksi=?,total=? WHERE id_laporan=?";
                PreparedStatement ubah = koneksi.connect.prepareStatement(sql);
                ubah.setString(1, txtjenis.getText());
                ubah.setString(2, txtnamapel.getText());
                ubah.setString(3, txttgl.getText());
                ubah.setString(4, txttotal.getText());
                ubah.setString(5, txtidlaporan.getText());
                ubah.executeUpdate();
                tampilDataLaporan();
                JOptionPane.showMessageDialog(this, "Data Telah Diubah");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
                
        try {
            if (
                    (txtidlaporan.getText().isEmpty()) &&
                    (txtjenis.getText().isEmpty()) &&
                    (txtnamapel.getText().isEmpty()) &&
                    (txttgl.getText().isEmpty()) &&
                    (txttotal.getText().isEmpty()) 
               ){
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Terlebih Dahulu");
            }else
            {
                String sql = "DELETE FROM laporan WHERE id_laporan=?";
                PreparedStatement hapus = koneksi.connect.prepareStatement(sql);
                hapus.setString(1, txtidlaporan.getText());
                hapus.executeUpdate();
                tampilDataLaporan();
                JOptionPane.showMessageDialog(this, "Data Telah Dihapus");
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameLaporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameLaporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnsimpanPrepare;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLaporan;
    private javax.swing.JTextField txtidlaporan;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtnamapel;
    private javax.swing.JTextField txttgl;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
