/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import database.koneksi;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rudia
 */
public class frameKasir extends javax.swing.JFrame {
        koneksi koneksi;
        
        public DefaultTableModel modelTableKasir;
    /**
     * Creates new form frameKasir
     */
    public frameKasir() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        koneksi = new koneksi();
        modelTableKasir = new DefaultTableModel();
        tableKasir.setModel(modelTableKasir);
        modelTableKasir.addColumn("Id Kasir");
        modelTableKasir.addColumn("Nama Admin");
        modelTableKasir.addColumn("No Telepon");
        tampilDataKasir();
    }
    
    public void tampilDataKasir(){
        try {
            modelTableKasir.getDataVector().removeAllElements();
            modelTableKasir.fireTableDataChanged();
            
            PreparedStatement query = koneksi.connect.prepareStatement("SELECT * FROM kasir");
            ResultSet data = query.executeQuery();
            while (data.next()) {                
                Object[] baris = new Object[3];
                baris[0] = data.getString("id_kasir");
                baris[1] = data.getString("nama_admin");
                baris[2] = data.getString("no_telp");
                modelTableKasir.addRow(baris);
            }
            query.close();
            data.close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtidkasir = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txttelepon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnsimpan = new javax.swing.JButton();
        btnsimpanprepare = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableKasir = new javax.swing.JTable();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id Kasir");

        jLabel2.setText("Nama Admin");

        txttelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteleponActionPerformed(evt);
            }
        });

        jLabel3.setText("Nomer Telpon");

        btnsimpan.setText("Simpan Statement");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnsimpanprepare.setText("simpan prepare stament");
        btnsimpanprepare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanprepareActionPerformed(evt);
            }
        });

        tableKasir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableKasir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKasirMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableKasir);

        btnubah.setText("Ubah Data");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus Data");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsimpanprepare))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtidkasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtidkasir, txtnama, txttelepon});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidkasir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnubah))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txttelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnsimpanprepare))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtteleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteleponActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
           try {
            if(txtidkasir.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "id belum diisi");
               txtidkasir.requestFocus();
            } else if(txtnama.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "nama admin belum diisi");
               txtnama.requestFocus();
            } else if(txttelepon.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "no telepon belum diisi");
               txttelepon.requestFocus();
            }else{
                String sql = "insert into kasir value('"+txtidkasir.getText()+"','"+txtnama.getText()+"','"+txttelepon.getText()+"')";
                koneksi.connect.createStatement().execute(sql);
                tampilDataKasir();
                JOptionPane.showMessageDialog(this, "data berhasil disimpan");
            }
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnsimpanprepareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanprepareActionPerformed
        // TODO add your handling code here:
      
           try {
            if(txtidkasir.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "id belum diisi");
               txtidkasir.requestFocus();
            } else if(txtnama.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "nama admin belum diisi");
               txtnama.requestFocus();
            } else if(txttelepon.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "no telepon belum diisi");
               txttelepon.requestFocus();
            } else{
                String sqlCari = "SELECT * FROM kasir WHERE id_kasir ='"+txtidkasir.getText()+"'";
               ResultSet cari = koneksi.connect.createStatement().executeQuery(sqlCari);
               if (cari.next()){
                    JOptionPane.showMessageDialog(this, "ID sudah terdaftar");
                                        
                       txtnama.setText(cari.getString(2));
                       txttelepon.setText(cari.getString(3));                   
               }else{
                    String sql = "INSERT INTO kasir VALUE(?,?,?)";
                    PreparedStatement simpan = koneksi.connect.prepareStatement(sql);
                    simpan.setString(1, txtidkasir.getText());
                    simpan.setString(2, txtnama.getText());
                    simpan.setString(3, txttelepon.getText());
                    simpan.executeUpdate();
                    tampilDataKasir();
                    JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
               }
               
           }  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnsimpanprepareActionPerformed

    private void tableKasirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKasirMouseClicked
        // TODO add your handling code here:
        
        int baris = tableKasir.getSelectedRow();
        String id = tableKasir.getValueAt(baris, 0).toString();
        String nama = tableKasir.getValueAt(baris, 1).toString();
        String telpon = tableKasir.getValueAt(baris, 2).toString();
        txtidkasir.setText(id);
        txtnama.setText(nama);
        txttelepon.setText(telpon);
    }//GEN-LAST:event_tableKasirMouseClicked

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        try {
            if (
                    (txtidkasir.getText().isEmpty()) &&
                    (txtnama.getText().isEmpty()) &&
                    (txttelepon.getText().isEmpty())
               ){
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Terlebih Dahulu");
            }else
            {
                String sql = "UPDATE kasir Set nama_admin=?,no_telp=? WHERE id_kurir=?";
                PreparedStatement ubah = koneksi.connect.prepareStatement(sql);
                ubah.setString(1, txtnama.getText());
                ubah.setString(2, txttelepon.getText());
                ubah.setString(3, txtidkasir.getText());
                ubah.executeUpdate();
                tampilDataKasir();
                JOptionPane.showMessageDialog(this, "Data Telah Diubah");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        
        try {
            if (
                    (txtidkasir.getText().isEmpty()) &&
                    (txtnama.getText().isEmpty()) &&
                    (txttelepon.getText().isEmpty()) 
               ){
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Terlebih Dahulu");
            }else
            {
                String sql = "DELETE FROM kasir WHERE id_kasir=?";
                PreparedStatement hapus = koneksi.connect.prepareStatement(sql);
                hapus.setString(1, txtidkasir.getText());
                hapus.executeUpdate();
                tampilDataKasir();
                JOptionPane.showMessageDialog(this, "Data Telah Dihapus");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnsimpanprepare;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tableKasir;
    private javax.swing.JTextField txtidkasir;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables
}
