/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;
import database.koneksi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rudia
 */
public class framePaketLaundry extends javax.swing.JFrame {
            
            koneksi koneksi;
            
            public DefaultTableModel modelTablePaket;

    /**
     * Creates new form framePaketLaundry
     */
    public framePaketLaundry() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        koneksi = new koneksi();
        modelTablePaket = new DefaultTableModel();
        tablePaket.setModel(modelTablePaket);
        modelTablePaket.addColumn("Id Paket");
        modelTablePaket.addColumn("Jenis Paket");
        modelTablePaket.addColumn("Harga Paket");
        modelTablePaket.addColumn("Antar Jemput");
        tampilDataPaket();
    }

     public void tampilDataPaket(){
        try {
            modelTablePaket.getDataVector().removeAllElements();
            modelTablePaket.fireTableDataChanged();
            
            PreparedStatement query = koneksi.connect.prepareStatement("SELECT * FROM paket_laundry");
            ResultSet data = query.executeQuery();
            while (data.next()) {                
                Object[] baris = new Object[4];
                baris[0] = data.getString("id_paket");
                baris[1] = data.getString("jenis_paket");
                baris[2] = data.getString("harga_paket");
                baris[3] = data.getString("antar_jemput");
                modelTablePaket.addRow(baris);
            }
            query.close();
            data.close();
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtidpaket = new javax.swing.JTextField();
        txtjenis = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtantar = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnSimpanPrepare = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePaket = new javax.swing.JTable();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Id Paket");

        txtidpaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpaketActionPerformed(evt);
            }
        });

        jLabel2.setText("Jenis Paket");

        jLabel3.setText("Harga Paket");

        jLabel4.setText("Antar Jemput");

        btnsimpan.setText("Simpan Statement");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnSimpanPrepare.setText("Simpan Prepare Statement");
        btnSimpanPrepare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPrepareActionPerformed(evt);
            }
        });

        tablePaket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePaketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePaket);

        btnubah.setText("Ubah Data");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus Data");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnsimpan)
                .addGap(34, 34, 34)
                .addComponent(btnSimpanPrepare)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtantar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnhapus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtidpaket, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtantar, txtharga, txtidpaket, txtjenis});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtidpaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnubah))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtantar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnSimpanPrepare))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidpaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpaketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpaketActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
         try {
            if(txtidpaket.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "id belum diisi");
               txtidpaket.requestFocus();
            } else if(txtjenis.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "jenis paket belum diisi");
               txtjenis.requestFocus();
            } else if(txtharga.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "harga belum diisi");
               txtharga.requestFocus();
            } else if(txtantar.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "antar jemput belum diisi");
               txtantar.requestFocus();   
            }else{
                String sql = "insert into paket_laundry value('"+txtidpaket.getText()+"','"+txtjenis.getText()+"','"+txtharga.getText()+"','"+txtantar.getText()+"')";
                koneksi.connect.createStatement().execute(sql);
                tampilDataPaket();
                JOptionPane.showMessageDialog(this, "data berhasil disimpan");
            }
        } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnSimpanPrepareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPrepareActionPerformed
        // TODO add your handling code here:
        try {
            if(txtidpaket.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "id belum diisi");
               txtidpaket.requestFocus();
            } else if(txtjenis.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Jenis Paket belum diisi");
               txtjenis.requestFocus();
            } else if(txtharga.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Harga Paket belum diisi");
               txtharga.requestFocus();
            } else if(txtantar.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Antar Jemput belum diisi");
               txtantar.requestFocus();
            } else{
               String sqlCari = "SELECT * FROM paket_laundry WHERE id_paket ='"+txtidpaket.getText()+"'";
               ResultSet cari = koneksi.connect.createStatement().executeQuery(sqlCari);
               if (cari.next()){
                    JOptionPane.showMessageDialog(this, "ID sudah terdaftar");
                                        
                       txtjenis.setText(cari.getString(2));
                       txtharga.setText(cari.getString(3));                   
                       txtantar.setText(cari.getString(4));                   
               }else{
                    String sql = "INSERT INTO paket_laundry VALUE(?,?,?,?)";
                    PreparedStatement simpan = koneksi.connect.prepareStatement(sql);
                    simpan.setString(1, txtidpaket.getText());
                    simpan.setString(2, txtjenis.getText());
                    simpan.setString(3, txtharga.getText());
                    simpan.setString(4, txtantar.getText());
                    simpan.executeUpdate();
                    tampilDataPaket();
                    JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
               }
               
           }  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnSimpanPrepareActionPerformed

    private void tablePaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePaketMouseClicked
        // TODO add your handling code here:
        
        int baris = tablePaket.getSelectedRow();
        String id = tablePaket.getValueAt(baris, 0).toString();
        String jenis = tablePaket.getValueAt(baris, 1).toString();
        String harga = tablePaket.getValueAt(baris, 2).toString();
        String antar = tablePaket.getValueAt(baris, 3).toString();
        txtidpaket.setText(id);
        txtjenis.setText(jenis);
        txtharga.setText(harga);
        txtantar.setText(antar);

    }//GEN-LAST:event_tablePaketMouseClicked

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        // TODO add your handling code here:
        try {
            if (
                    (txtidpaket.getText().isEmpty()) &&
                    (txtjenis.getText().isEmpty()) &&
                    (txtharga.getText().isEmpty()) &&
                    (txtantar.getText().isEmpty()) 
               ){
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Terlebih Dahulu");
            }else
            {
                String sql = "UPDATE paket_laundry Set jenis_paket=?,harga_paket=?,antar_jemput=? WHERE id_paket=?";
                PreparedStatement ubah = koneksi.connect.prepareStatement(sql);
                ubah.setString(1, txtjenis.getText());
                ubah.setString(2, txtharga.getText());
                ubah.setString(3, txtantar.getText());
                ubah.setString(4, txtidpaket.getText());                
                ubah.executeUpdate();
                tampilDataPaket();
                JOptionPane.showMessageDialog(this, "Data Telah Diubah");
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
                        
        try {
            if (
                    (txtidpaket.getText().isEmpty()) &&
                    (txtjenis.getText().isEmpty()) &&
                    (txtharga.getText().isEmpty()) &&
                    (txtantar.getText().isEmpty()) 
               ){
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Terlebih Dahulu");
            }else
            {
                String sql = "DELETE FROM paket_laundry WHERE id_paket=?";
                PreparedStatement hapus = koneksi.connect.prepareStatement(sql);
                hapus.setString(1, txtidpaket.getText());
                hapus.executeUpdate();
                tampilDataPaket();
                JOptionPane.showMessageDialog(this, "Data Telah Dihapus");
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePaketLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePaketLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePaketLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePaketLaundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePaketLaundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpanPrepare;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePaket;
    private javax.swing.JTextField txtantar;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtidpaket;
    private javax.swing.JTextField txtjenis;
    // End of variables declaration//GEN-END:variables
}
